# labels to be used with /area command
area:
  - 'bug'
  - 'important'

major:
- '/\/label major/'
minor:
- '/\/label minor/'
patch:
- '/\/label patch/'

do-not-merge:
- '/\/hold/'
- '/\/do-not-merge/'
feature:
- '/\/label feature/'
bug:
- '/\/label bug/'
maintenance:
- '/\/label maintenance/'
