name: "CI Actions"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.1 #May not be the latest version
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labels.yaml
          enable-versioned-regex: 0
          include-title: 1
          sync-labels: 1

      - uses: wow-actions/wip@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labels: "do-not-merge"
