name: "CI Actions"
on:
  issue_comment:
    types: [created]
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@main
        if: github.event.issue.pull_request && contains(github.event.comment.body, '/')
        with:
          prow-commands: "/assign
            /unassign
            /approve
            /retitle
            /area
            /kind
            /priority
            /remove
            /lgtm
            /close
            /reopen
            /lock
            /milestone
            /hold
            /cc
            /uncc"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: wow-actions/wip@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          labels: "hold"
